apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificate-viewer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certificate-viewer
  template:
    metadata:
      labels:
        app: certificate-viewer
    spec:
      containers:
      - name: certificate-viewer
        image: khizraghaffar/certificate-viewer:1.2
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: certificate-viewer-service
spec:
  type: NodePort
  selector:
    app: certificate-viewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007  # Choose a port between 30000-32767
